### ISSUE TITLE
Deadlock in Ruby-2.5.1 (MRI)

### ISSUE THREAD

**Issue by larskanis** [larskanis/eventbox#2]
Several action tests fails sometimes with deadlock error, although there shouldn't be a deadlock. I managed to find a reproducible test case which fails with a 50% chance. It is on the [deadlock branch](https://github.com/larskanis/eventbox/tree/deadlock) and fails like so:

```
$ ruby -Ilib test/eventbox/timer_test.rb -v -n test_all_repeated
Run options: -v -n test_all_repeated --seed 56879

# Running:

EventboxTimerTest#test_all_repeated = Exception
["559925ce4b68", :lock, "/home/lars/comcard/eventbox/lib/eventbox.rb:82:in `initialize'"]
["559925ce4b68", :locked]
["559925ce4b68", :unlock]
["559925ce4b68", :unlocked]
["559925ce4b68", :time_at]
["559925ce4b68", :lock, "test/eventbox/timer_test.rb:86:in `block in test_after'"]
["559925ce4b68", :locked]
["559926431e70", :next, 1970-01-01 01:00:00 +0100]
["559926431e70", :lock, "/home/lars/comcard/eventbox/lib/eventbox/timer.rb:84:in `block in timer_start_worker'"]
["559925ce4b68", :raise, "559926431e70"]
["559925ce4b68", :raise, "559926431e70"]
["559925ce4b68", :unlock]
["559925ce4b68", :unlocked]
["559926431e70", :locked]
["559925ce4b68", :excpetion, fatal]
["559925ce4b68", :time_normal]
["559926431e70", :unlock]
["559926431e70", :unlocked]
["559926431e70", :interval, -1541282546.1500416]
["559926431e70", :lock, "/home/lars/comcard/eventbox/lib/eventbox/timer.rb:96:in `block in timer_start_worker'"]
["559926431e70", :locked]
["559926431e70", :fire, 2018-11-03 23:02:28 +0100]
["559926431e70", :unlock]
["559926431e70", :unlocked]
["559926431e70", :next, 2018-11-03 23:02:28 +0100]
["559926431e70", :lock, "/home/lars/comcard/eventbox/lib/eventbox/timer.rb:84:in `block in timer_start_worker'"]
["559926431e70", :locked]
["559926431e70", :unlock]
["559926431e70", :unlocked]
["559926431e70", :interval, 0.999148958]
["559926431e70", :reload]
["559926431e70", :next, 2018-11-03 23:02:28 +0100]
["559926431e70", :lock, "/home/lars/comcard/eventbox/lib/eventbox/timer.rb:84:in `block in timer_start_worker'"]
["559926431e70", :locked]
["559926431e70", :unlock]
["559926431e70", :unlocked]
["559926431e70", :interval, 0.998664239]
["559926431e70", :reload]
["559926431e70", :next, 2018-11-03 23:02:28 +0100]
["559926431e70", :lock, "/home/lars/comcard/eventbox/lib/eventbox/timer.rb:84:in `block in timer_start_worker'"]
["559926431e70", :locked]
["559926431e70", :unlock]
["559926431e70", :unlocked]
["559926431e70", :interval, 0.998205882]
0.22 s = E

Finished in 0.225489s, 4.4348 runs/s, 0.0000 assertions/s.

  1) Error:
EventboxTimerTest#test_all_repeated:
fatal: No live threads left. Deadlock?
4 threads, 4 sleeps current:0x000055992641d040 main thread:0x0000559925c92ff0
* #<Thread:0x0000559925ce4b68 sleep_forever>
   rb_thread_t:0x0000559925c92ff0 native:0x00007fc8679f2740 int:0
   /home/lars/comcard/eventbox/lib/eventbox/argument_sanitizer.rb:207:in `pop'
   /home/lars/comcard/eventbox/lib/eventbox/argument_sanitizer.rb:207:in `block in callback_loop'
   /home/lars/comcard/eventbox/lib/eventbox/argument_sanitizer.rb:206:in `loop'
   /home/lars/comcard/eventbox/lib/eventbox/argument_sanitizer.rb:206:in `callback_loop'
   /home/lars/comcard/eventbox/lib/eventbox/boxable.rb:108:in `block in yield_call'
   test/eventbox/timer_test.rb:86:in `block in test_after'
   test/eventbox/timer_test.rb:35:in `block (2 levels) in with_fake_time'
   /home/lars/.rvm/gems/ruby-2.5.1/gems/minitest-5.11.3/lib/minitest/mock.rb:234:in `stub'
   test/eventbox/timer_test.rb:34:in `block in with_fake_time'
   /home/lars/.rvm/gems/ruby-2.5.1/gems/minitest-5.11.3/lib/minitest/mock.rb:234:in `stub'
   test/eventbox/timer_test.rb:33:in `with_fake_time'
   test/eventbox/timer_test.rb:85:in `test_after'
   test/eventbox/timer_test.rb:182:in `block in test_all_repeated'
   test/eventbox/timer_test.rb:181:in `times'
   test/eventbox/timer_test.rb:181:in `test_all_repeated'
   /home/lars/.rvm/gems/ruby-2.5.1/gems/minitest-5.11.3/lib/minitest/test.rb:98:in `block (3 levels) in run'
   /home/lars/.rvm/gems/ruby-2.5.1/gems/minitest-5.11.3/lib/minitest/test.rb:195:in `capture_exceptions'
   /home/lars/.rvm/gems/ruby-2.5.1/gems/minitest-5.11.3/lib/minitest/test.rb:95:in `block (2 levels) in run'
   /home/lars/.rvm/gems/ruby-2.5.1/gems/minitest-5.11.3/lib/minitest.rb:265:in `time_it'
   /home/lars/.rvm/gems/ruby-2.5.1/gems/minitest-5.11.3/lib/minitest/test.rb:94:in `block in run'
   /home/lars/.rvm/gems/ruby-2.5.1/gems/minitest-5.11.3/lib/minitest.rb:360:in `on_signal'
   /home/lars/.rvm/gems/ruby-2.5.1/gems/minitest-5.11.3/lib/minitest/test.rb:211:in `with_info_handler'
   /home/lars/.rvm/gems/ruby-2.5.1/gems/minitest-5.11.3/lib/minitest/test.rb:93:in `run'
   /home/lars/.rvm/gems/ruby-2.5.1/gems/minitest-5.11.3/lib/minitest.rb:960:in `run_one_method'
   /home/lars/.rvm/gems/ruby-2.5.1/gems/minitest-5.11.3/lib/minitest.rb:334:in `run_one_method'
   /home/lars/.rvm/gems/ruby-2.5.1/gems/minitest-5.11.3/lib/minitest.rb:321:in `block (2 levels) in run'
   /home/lars/.rvm/gems/ruby-2.5.1/gems/minitest-5.11.3/lib/minitest.rb:320:in `each'
   /home/lars/.rvm/gems/ruby-2.5.1/gems/minitest-5.11.3/lib/minitest.rb:320:in `block in run'
   /home/lars/.rvm/gems/ruby-2.5.1/gems/minitest-5.11.3/lib/minitest.rb:360:in `on_signal'
   /home/lars/.rvm/gems/ruby-2.5.1/gems/minitest-5.11.3/lib/minitest.rb:347:in `with_info_handler'
   /home/lars/.rvm/gems/ruby-2.5.1/gems/minitest-5.11.3/lib/minitest.rb:319:in `run'
   /home/lars/.rvm/gems/ruby-2.5.1/gems/minitest-5.11.3/lib/minitest.rb:159:in `block in __run'
   /home/lars/.rvm/gems/ruby-2.5.1/gems/minitest-5.11.3/lib/minitest.rb:159:in `map'
   /home/lars/.rvm/gems/ruby-2.5.1/gems/minitest-5.11.3/lib/minitest.rb:159:in `__run'
   /home/lars/.rvm/gems/ruby-2.5.1/gems/minitest-5.11.3/lib/minitest.rb:136:in `run'
   /home/lars/.rvm/gems/ruby-2.5.1/gems/minitest-5.11.3/lib/minitest.rb:63:in `block in autorun'
* #<Thread:0x00005599262962a0@/home/lars/.rvm/gems/ruby-2.5.1/gems/minitest-5.11.3/lib/minitest/parallel.rb:28 sleep_forever>
   rb_thread_t:0x00005599263fe390 native:0x00007fc86408f700 int:0
   /home/lars/.rvm/gems/ruby-2.5.1/gems/minitest-5.11.3/lib/minitest/parallel.rb:30:in `pop'
   /home/lars/.rvm/gems/ruby-2.5.1/gems/minitest-5.11.3/lib/minitest/parallel.rb:30:in `block (2 levels) in start'
* #<Thread:0x0000559926295f58@/home/lars/.rvm/gems/ruby-2.5.1/gems/minitest-5.11.3/lib/minitest/parallel.rb:28 sleep_forever>
   rb_thread_t:0x00005599263fedf0 native:0x00007fc863e8d700 int:0
   /home/lars/.rvm/gems/ruby-2.5.1/gems/minitest-5.11.3/lib/minitest/parallel.rb:30:in `pop'
   /home/lars/.rvm/gems/ruby-2.5.1/gems/minitest-5.11.3/lib/minitest/parallel.rb:30:in `block (2 levels) in start'
* #<Thread:0x0000559926431e70@/home/lars/comcard/eventbox/lib/eventbox/event_loop.rb:284 sleep_forever>
   rb_thread_t:0x000055992641d040 native:0x00007fc863c8b700 int:0
   /home/lars/comcard/eventbox/lib/eventbox/event_loop.rb:110:in `lock'
   /home/lars/comcard/eventbox/lib/eventbox/event_loop.rb:110:in `with_call_frame'
   /home/lars/comcard/eventbox/lib/eventbox/event_loop.rb:137:in `sync_call'
   /home/lars/comcard/eventbox/lib/eventbox/boxable.rb:80:in `block in sync_call'
   /home/lars/comcard/eventbox/lib/eventbox/timer.rb:84:in `block in timer_start_worker'
   /home/lars/comcard/eventbox/lib/eventbox/timer.rb:81:in `loop'
   /home/lars/comcard/eventbox/lib/eventbox/timer.rb:81:in `timer_start_worker'
   /home/lars/comcard/eventbox/lib/eventbox/event_loop.rb:290:in `call'
   /home/lars/comcard/eventbox/lib/eventbox/event_loop.rb:290:in `block (3 levels) in _start_action'
   /home/lars/comcard/eventbox/lib/eventbox/event_loop.rb:286:in `handle_interrupt'
   /home/lars/comcard/eventbox/lib/eventbox/event_loop.rb:286:in `block (2 levels) in _start_action'

    /home/lars/comcard/eventbox/lib/eventbox/argument_sanitizer.rb:207:in `pop'
    /home/lars/comcard/eventbox/lib/eventbox/argument_sanitizer.rb:207:in `block in callback_loop'
    /home/lars/comcard/eventbox/lib/eventbox/argument_sanitizer.rb:206:in `loop'
    /home/lars/comcard/eventbox/lib/eventbox/argument_sanitizer.rb:206:in `callback_loop'
    /home/lars/comcard/eventbox/lib/eventbox/boxable.rb:108:in `block in yield_call'
    test/eventbox/timer_test.rb:86:in `block in test_after'
    test/eventbox/timer_test.rb:35:in `block (2 levels) in with_fake_time'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

**Comment by larskanis** [comment]
Ruby-2.5.3 and ruby-2.4.5 fix the above issue. I bisected the commits and found that the fixing commit is https://github.com/ruby/ruby/commit/c561f04beb2e227d03e91534b6ed38a8ee540b91 . The commit is not backported to ruby-2.3 since it's in security maintenance phase now.

Maybe it's a good idea to print a warning, if `RUBY_ENGINE=ruby` the `RUBY_VERSION` is below the fixed versions.
